In [3]:
import numpy as np
import torch

In [5]:
x = torch.rand(3,2)
x

tensor([[0.8566, 0.1020],
        [0.6074, 0.5386],
        [0.2455, 0.7551]])

In [6]:
x.size()

torch.Size([3, 2])

In [7]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [8]:
z = x + y
z

tensor([[1.8566, 1.1020],
        [1.6074, 1.5386],
        [1.2455, 1.7551]])

In [9]:
z[0]

tensor([1.8566, 1.1020])

In [10]:
z[:, 1:]

tensor([[1.1020],
        [1.5386],
        [1.7551]])

In [11]:
z.resize_(2,3)

tensor([[1.8566, 1.1020, 1.6074],
        [1.5386, 1.2455, 1.7551]])

In [12]:
z

tensor([[1.8566, 1.1020, 1.6074],
        [1.5386, 1.2455, 1.7551]])

In [13]:
a = np.random.rand(4,3)
a

array([[0.73817922, 0.25262333, 0.11083226],
       [0.61869607, 0.19538099, 0.09363442],
       [0.55157561, 0.23591319, 0.18373256],
       [0.03115276, 0.08487242, 0.90758364]])

In [14]:
b = torch.from_numpy(a)
b

tensor([[0.7382, 0.2526, 0.1108],
        [0.6187, 0.1954, 0.0936],
        [0.5516, 0.2359, 0.1837],
        [0.0312, 0.0849, 0.9076]], dtype=torch.float64)

In [15]:
b.numpy()

array([[0.73817922, 0.25262333, 0.11083226],
       [0.61869607, 0.19538099, 0.09363442],
       [0.55157561, 0.23591319, 0.18373256],
       [0.03115276, 0.08487242, 0.90758364]])